version: '3.5'
services:
    detector:
        build:
            context: ./detector/
            dockerfile: Dockerfile
        volumes:
            - ./detector/:/usr/src/app
        ports:
            - "7000:7000"
        environment:
            - "PYTHONUNBUFFERED=1"
        links:
            - redis:redis
        depends_on:
            - redis
    redis:
        image: "redis:6.0.8-alpine"
        expose:
            - "6379"