version: '3.5'
services:
    detector:
        build:
            context: ./detector
            dockerfile: Dockerfile
        volumes:
            - ./detector:/usr/src/app
            - ./shared:/usr/src/shared
        ports:
            - "7000:7000"
        environment:
            - "PYTHONUNBUFFERED=1"
        links:
            - redis:redis
        depends_on:
            - redis
            - mq
    api:
        build:
            context: ./api
            dockerfile: Dockerfile.dev
        ports:
            - '7001:7001'
        volumes:
            - ./api:/usr/src/app
            - ./shared:/usr/src/shared
        environment:
            NODE_ENV: production
            PORT: 7001
        links:
            - redis:redis
        depends_on:
            - redis
            - mq
    redis:
        image: "redis:6-alpine"
    mq:
        image: rabbitmq:3-alpine